[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "echo '=== FILES IN PRISMA ===' && ls -la prisma/ && echo '=== FILES IN DIST ===' && ls dist/ && echo '=== RUNNING MIGRATE ===' && npx prisma migrate deploy && echo '=== RUNNING SEED ===' && node prisma/seed-production.js && echo '=== STARTING SERVER ===' && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
